name: base_ui_m3
version: 1.0.0+1
publish_to: none
description: This is a Flutter application in UI development that refers to the base ThemeData of Flutter Material itself, from the use of textStyle to the selection of colors taken from the default ThemeData.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_web_frame: ^1.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    
  fonts:
    - family: google
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf